title: Nathen Huang # your name (or website title) here
logo: "/images/portrait.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <h2>About me:</h2>
  Hi there! I'm Nathen- a quantitative social scientist based in Washington, DC. By day, I'm a consulting data scientist at KPMG. By night, I'm passionate about applying traditional statistics and theory-driven machine learning to study social problems.
  <br><br>
  Check out my:
  <br><br>
  <a href="/pdf/resume_05_15_20.pdf">CV</a> | <a href="https://www.linkedin.com/in/nathenphuang/">LinkedIn</a> | <a href="https://www.github.com/natepeteyellow">GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
