title: Nathen Huang # your name (or website title) here
logo: "/images/portrait.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <h2>About me:</h2>
  Hi there, I'm Nathen- a quantitative social scientist based in Washington, DC. I'm fascinated with interpersonal dynamics and leveraging statistics to model social networks. In a previous life I studied studied experimental psychology and applied statistics at Columbia; these days I'm intrigued by traditional statistics and theory-driven machine learning.
  <br><br>
  Check me out on:
  <ul><a href="https://www.linkedin.com/in/nathenphuang/">LinkedIn</a></ul>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
